record:
  repo_id: &repo_id "scylearning/move_reagent_bottle" 
  # repo_id: &repo_id "scylearning/move_test_tube" 
  # repo_id: &repo_id "scylearning/pick_greencube_into_trashbin" 
  # Suggested format: <hf_username>/<description>, description = task.description -> Verb_SourceObject_prep_TargetObject
  # e.g. Pick up the green cube and put it into the trash bin -> pick_greencube_into_trashbin
  debug: &debug False # if True, robot will not execute any actions, but gripper can still be controlled
  user_notes:  # any additional notes about the dataset
  fps: 15 # dataset and camera frame rate

  teleop:
    control_mode: "isoteleop"
    dynamixel_config:
      port: "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0"
      hardware_offsets: [-216.65, -281.865, -233.085, -281.25, 47.11, -158.466] # The Calibration offsets between the master and the slave robot
      use_gripper: &use_gripper True # whether the slave robot can use gripper
      joint_ids: [1, 2, 3, 4, 5, 6]
      joint_offsets: [0.0, 0.0, -3.142, 0.0, 0.0, 0.0]
      joint_signs: [1, 1, -1, 1, 1, 1]
      gripper_config: [7, 2.5157, 3.4790] # id, min, max
      
  robot:
    ip: &ip "192.168.131.11" # robot_ip
    use_gripper: *use_gripper
    close_threshold: 0.7 # threshold to determine gripper open/close
    gripper_bin_threshold: 0.98 # threshold to determine gripper is closed
    gripper_port: &gripper_port "/dev/ur5e_left_gripper" # gripper_port
    gripper_reverse: &gripper_reverse False  # If gripper moves opposite, flip this value
    control_space: "force" # "force" or "joint"
    robot_urdf_path: assets/urdf/ur5e.urdf
    force_mode:
      kp: 2000 
      kd: 200 
      kp_rot: 4000
      kd_rot: 800
      rtde_freq: 125
      select_vector: [1, 1, 1, 1, 1, 1]
      force_limit: [2,2,2,2,2,2]
      pos_delta: 0.2
      vel_delta: 0.2   
      gain_scale: 1.5
    joint_mode:
      look_ahead_time: 0.2
      dt: 0.002
      gain: 100

  task:
    description: "Move the reagent bottle to the diagonal position of the bottle rack." # task description
    # description: "Move the test tube from one side of the rack to the other." # task description
    num_episodes: 2 # number of episodes to record
    display: True # Whether to display the data during recording
    resume: True
    resume_dataset: scylearning/move_reagent_bottle_20260317_v01 # dataset to resume from if resume is True

  time:
    episode_time_sec: 6000 # max time per episode in seconds
    reset_time_sec: 6000 # max time to reset between episodes in seconds
    save_meta_period: 1 # Save metadata after every N episodes

  cameras:
    wrist_cam_serial: "151222071369" # wrist camera serial number
    exterior_cam_serial: "151322070364" # exterior camera serial number
    width: 424 # 640 424
    height: 240 # 360 240

  storage:
    push_to_hub: False # whether to push the dataset to your huggingface repo after recording

replay:
  dataset_name: scylearning/pick_greencube_into_trashbin_20251102_v01
  episode_idx: 0 # episode index to replay
  debug: *debug
  robot:
    ip: *ip
    gripper_port: *gripper_port
    use_gripper: *use_gripper
    gripper_reverse: *gripper_reverse

visualize:
  dataset_name: scylearning/move_reagent_bottle_20260317_v01
  episode_index: 100 # episode index to visualize

check_dataset:
  dataset_name: scylearning/move_reagent_bottle_20260317_v01

prune_episodes:
  old_dataset_name: scylearning/move_reagent_bottle_20260317_v01
  new_dataset_name: scylearning/move_reagent_bottle_20260317_v01_pruned